basePath: "E:/workspace/project/sanitary-inspection-be/sanitary-inspection-core-biz"
basePackage: com.microsun.inspection.core.biz
domain:
  entity:
    suffix: DO
    package: domain.entity
  dto:
    suffix: DTO
    package: domain.dto
  query:
    suffix: Query
    package: domain.dto
  vo:
    suffix: VO
    package: domain.vo
  listVo:
    suffix: ListVO
    package: domain.vo
mapper:
  suffix: Mapper
  package: mapper
service:
  interface:
    suffix: Service
    package: service
  impl:
    suffix: ServiceImpl
    package: service.impl
controller:
  suffix: Controller
  package: controller
  basePath:
  basePackage:






